// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	a[0] = "body_opforce_arctic_smg";
	a[1] = "body_opforce_arctic_smg_b";
	a[2] = "body_opforce_arctic_smg_b_l1";
	a[3] = "body_opforce_arctic_smg_c";
	a[4] = "body_opforce_arctic_smg_c_l1";
	a[5] = "body_opforce_arctic_smg_l1";
	return a;
}
