// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	a[0] = "body_airborne_assault_a";
	a[1] = "body_airborne_assault_a_noik";
	a[2] = "body_airborne_assault_b";
	a[3] = "body_airborne_assault_b_noik";
	a[4] = "body_airborne_assault_c";
	a[5] = "body_airborne_assault_c_noik";
	return a;
}
