// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	a[0] = "body_opforce_arctic_assault_a";
	a[1] = "body_opforce_arctic_assault_a_l1";
	a[2] = "body_opforce_arctic_assault_b";
	a[3] = "body_opforce_arctic_assault_b_l1";
	a[4] = "body_opforce_arctic_assault_c";
	a[5] = "body_opforce_arctic_assault_c_l1";
	return a;
}
