// H2 GSC SOURCE
// Generated by https://github.com/xensik/gsc-tool

main()
{
    var_0[0] = "head_opforce_arctic_a_L1";
    var_0[1] = "head_opforce_arctic_b_L1";
    var_0[2] = "head_opforce_arctic_c_L1";
    var_0[3] = "head_opforce_arctic_d_L1";
    var_0[4] = "head_opforce_arctic_a";
    var_0[5] = "head_opforce_arctic_b";
    var_0[6] = "head_opforce_arctic_c";
    var_0[7] = "head_opforce_arctic_d";
    return var_0;
}
