// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	a[0] = "body_opforce_arctic_shotgun";
	a[1] = "body_opforce_arctic_shotgun_b";
	a[2] = "body_opforce_arctic_shotgun_b_l1";
	a[3] = "body_opforce_arctic_shotgun_c";
	a[4] = "body_opforce_arctic_shotgun_c_l1";
	a[5] = "body_opforce_arctic_shotgun_l1";
	return a;
}
