// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_force_b_woodland");
	self attach("head_force_chad", "", true);
	self.headModel = "head_force_chad";
	self.voice = "british";
}

precache()
{
	precacheModel("body_force_b_woodland");
	precacheModel("head_force_chad");
}
