// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_force_assault_woodland");
	self attach("head_force_c", "", true);
	self.headModel = "head_force_c";
	self.voice = "american";
}

precache()
{
	precacheModel("body_force_assault_woodland");
	precacheModel("head_force_c");
}
