// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	codescripts\character::setModelFromArray(xmodelalias\alias_milita_bodies::main());
	codescripts\character::attachHead( "alias_milita_heads", xmodelalias\alias_milita_heads::main() );
	self.voice = "arab";
	self setclothtype( "vestlight" );
}

precache()
{
	codescripts\character::precacheModelArray(xmodelalias\alias_milita_bodies::main());
	codescripts\character::precacheModelArray(xmodelalias\alias_milita_heads::main());
}
