// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_op_airborne_sniper");
	self attach( "head_op_airborne_sniper", "", 1 );
	self.voice = "russian";
}

precache()
{
	precacheModel("body_op_airborne_sniper");
	precacheModel("head_op_airborne_sniper");
}
