// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_force_c_woodland");
	self attach("head_force_assault", "", true);
	self.headModel = "head_force_assault";
	self.voice = "british";
}

precache()
{
	precacheModel("body_force_c_woodland");
	precacheModel("head_force_assault");
}
